grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      labelValue: "1"
    datasources:
      enabled: true
      labelValue: "1"
      searchNamespace: ALL
  plugins:
    - grafana-piechart-panel
